### ISSUE TITLE
根据使用场景的功能增强

### ISSUE THREAD

**Issue by LittleNightmare** [Bluefissure/MapLinker#1]
根据跟4.0A怪车的经历，发现MapLinker不光找怪方便，跟车也很方便。希望可以增加/改进如下功能：
1. Tel可以选择传送卷，如从基拉巴尼亚到奥萨德
2. Tel增加一个距离判断，计算当前坐标到目标点，和水晶到目标点的距离，哪个更近（能算出传送花费时间更好，就是传送5s+加载时间可以飞多远）如果飞过去更快，提示不要传送 ~~（脑死亡轮椅）~~
2. 可以设置单位时间内，设定不捕获一个人的说话或，
3. 指定车头（跟车）模式，只选择一个玩家作为捕获目标，捕获不同的坐标点（一般两个狩猎怪的直线距离不超过，即两个坐标直线距离小于3，可以认定为一个狩猎怪）
4. 都不加的话，把clear按钮放到前面吧。因为每次车头喊话较长（对卫月窗口来说），导致clear按钮偏下

**Comment by Bluefissure** [comment]
1. 这个应该可以在teleport插件中进行设置
2. 没必要吧感觉……一般看一眼地图和关掉提示的不要传送窗口耗费的时间也差不多
3.4. 可以考虑一个去重的功能
5. 可以

**Comment by LittleNightmare** [comment]
1. 瞎了，平时指令用习惯了
2. 关掉提示和看一眼地图差不多，但是如果传送划算就没有提示，可以不看了 ~~写代码的时间增加了.jpg~~（好吧，其实也没那么有用）
3. \獭爹/\獭爹/\獭爹/
4. \獭爹/\獭爹/\獭爹/
5. \獭爹/\獭爹/\獭爹/
6. 捕获的坐标点可以手动排序，不知道卫月的窗口支不支持。这个应该算是给车头车头排一下顺序（或者采集职业玩家方便点击？但觉得用tp的比较好）

**Comment by Bluefissure** [comment]
[v1.0.3.1](https://github.com/Bluefissure/MapLinker/releases/tag/v1.0.3.1) 把 clear 按钮上移了，并添加了过滤超时的设置。
