### ISSUE TITLE
Changelog Tab - Crashing

### ISSUE THREAD

**Issue by Kherae** [Bluefissure/MapLinker#15]
currently, this addon is causing loading the changelog tab in the plugin manager to cause a hard CTD without error. This is because of the usage of %s in the string, as that is often used in string replacement. removing it fixes the issue.

**Comment by Bluefissure** [comment]
I think it's fixed in the current Dalamud, in https://github.com/goatcorp/Dalamud/commit/623327d407a3816d9fa35f8db7bda683c5a1719b
