### ISSUE TITLE
"Filter out duplicates" should filter based on map link data, not chat message text

### ISSUE THREAD

**Issue by allainecactuar** [Bluefissure/MapLinker#2]
MapLinker provides a "Filter out duplicates" option, but that filters based on the entire message text, not just the map link. This means if flags are relayed and different people have different text in their macros, the flag will still show up multiple times. For example:

![image](https://user-images.githubusercontent.com/52390292/104241392-78eeea00-5412-11eb-8bf9-f0d845ba2645.png)

Here's the existing code that implements it:

https://github.com/Bluefissure/MapLinker/blob/2a52243f9e96eac05eb79ba47a34bc5c324b33cf/MapLinker/MapLinker.cs#L161

I would suggest that this setting should prevent duplicate flag values from being logged for 5 minutes (or some other smallish amount of time), so that a bunch of relays of the same flags will be filtered, but then something else interesting at that flag later could be logged. 

Thanks. Great plugin!

**Comment by Bluefissure** [comment]
resolve in https://github.com/Bluefissure/MapLinker/commit/e1ae7708c001ec36558120b2199c415597923db0, with a drag input for the filter timeout
![quicker_746e316a-774c-46ba-88f7-ff46f577bc2d.png](https://i.loli.net/2021/01/12/dQbR9w4sJFTUEY3.png)

**Comment by allainecactuar** [comment]
👍
