### ISSUE TITLE
Plugin outdated

### ISSUE THREAD

**Issue by Peanut84** [Bluefissure/MapLinker#20]
After 6.2 needs update.
Ty so much in advance :) You're plugin is one of the best.

**Comment by Bluefissure** [comment]
Thank you, I was aware of the update to API level but Sumeru took most of my time these days, will take some time today to update & test all of my plugins in the main repo today.

**Comment by Bluefissure** [comment]
Will be there after https://github.com/goatcorp/DalamudPluginsD17/pull/252 get merged

**Comment by Bluefissure** [comment]
merged, should be able to update
