### ISSUE TITLE
update Needed 6.0

### ISSUE THREAD

**Issue by DiggityMan420** [Bluefissure/MapLinker#7]
No showing up as updated to 6.0

**Comment by Bluefissure** [comment]
What is not showing up?

**Comment by DiggityMan420** [comment]
see [PIC](https://imgshare.io/image/rpROxd)

**Comment by Bluefissure** [comment]
![image](https://user-images.githubusercontent.com/9719003/145681421-81be90b7-1ed5-47ea-98b8-4f3345336343.jpeg)
Good on my side.
