### ISSUE TITLE
Teleport function not working

### ISSUE THREAD

**Issue by Slightlyxz** [Bluefissure/MapLinker#8]
Whenever I try to teleport to a region using maplinker a small window pops up telling me to restart my game, no error message in chat.
After restarting, the same error still occurs.
Got both Teleporter and Chatcoordinates installed as well.

Is there any sort of log I could provide or my plugin list?

**Comment by Bluefissure** [comment]
What kind of error window? Can you upload your dalamud.log and the screenshot of the window?

**Comment by Slightlyxz** [comment]
![ffxiv_dx11_AN7wHlK8hZ](https://user-images.githubusercontent.com/80231852/145859360-21930b04-f565-456d-9813-d81972d6096b.png)

I can only upload a old log right now, hope it will help. If needed I can send a more recent one in around 7 hours when the queues for my world are low again.

https://file.io/JuKGXPAGY3F3

Let me know if you need a cleaner log / more information!

**Comment by Bluefissure** [comment]
> https://file.io/JuKGXPAGY3F3

It says the file is deleted.

**Comment by Slightlyxz** [comment]
https://file.io/SjP2eVRAPARG does it work now?

**Comment by Bluefissure** [comment]
> https://file.io/SjP2eVRAPARG does it work now?

Yes, it works.

According to the log file, it seems that sth wrong with the Lumina data fetching, I'll take a look later tonight.

Thanks for pointing it out.

**Comment by Bluefissure** [comment]
This should be fixed after https://github.com/goatcorp/DalamudPlugins/pull/1686 get merged.
